---
# https://redis.io/topics/admin

- name: keydb-cluster-operating-system-tweaks | Set vm.overcommit_memory to 1
  sysctl:
    name: "vm.overcommit_memory"
    value: '1'
    sysctl_file: /etc/sysctl.d/65-keydb.conf
    state: present
    reload: yes

- name: keydb-cluster-operating-system-tweaks | Set vm.swappiness to 5
  sysctl:
    name: "vm.swappiness"
    value: '5'
    sysctl_file: /etc/sysctl.d/65-keydb.conf
    state: present
    reload: yes


- name: keydb-cluster-operating-system-tweaks | Persistence disable Transparent Huge Pages (THP)
  lineinfile:
    dest: '/etc/rc.d/rc.local'
    insertbefore: "touch /var/lock/subsys/local"
    regexp: '^echo never (.*) /sys/kernel/mm/transparent_hugepage/enabled'
    line: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'

- name: keydb-cluster-operating-system-tweaks | Set rc.local execution
  file: path=/etc/rc.d/rc.local state=file mode=0755

- name: keydb-cluster-operating-system-tweaks | Check if Tansparent Huge Pages (THP)  is disabled
  shell: >
    cat /sys/kernel/mm/transparent_hugepage/enabled
  changed_when: false
  register: thp_status

- name: keydb-cluster-operating-system-tweaks | On the fly disable Transparent Huge Pages (THP)
  shell: |
    echo "never" >> /sys/kernel/mm/transparent_hugepage/enabled
  changed_when: false
  when: thp_status.stdout is not search('never')