---
- name: keydb-cluster-configure | Apply config files /etc/keydb/keydb.conf
  ansible.builtin.template:
    src: etc/keydb/keydb.conf.j2
    dest: /etc/keydb/keydb.conf
    mode: 0644
    owner: keydb
    group: keydb
  notify: Warning file /etc/keydb/keydb.conf has been changed

- name: keydb-cluster-configure | Ensures KeyDB is started and enabled
  ansible.builtin.systemd:
    name: keydb
    daemon_reload: True
    enabled: True
    state: started