---
- import_tasks: keydb-cluster-operating-system-tweaks.yml
  tags: [keydb-cluster-operating-system-tweaks, operating-system-tweaks]

- include_tasks: keydb-cluster-install-{{ ansible_os_family }}.yml
  tags: [keydb-cluster-install, install]

- import_tasks: keydb-cluster-configure.yml
  tags: [keydb-cluster-configure, configure]

- import_tasks: keydb-cluster-create-cluster.yml
  tags: [keydb-cluster-create-cluster, create-cluster]

- import_tasks: keydb-cluster-redis-exporter.yml
  tags: [keydb-cluster-redis-exporter, redis-exporter]